---

- name: Update system package manager
  apt: 
    update_cache: yes
  become: yes

- name: Installing system deps
  apt: 
    name:
      "{{apt_pkg_deps}}"
    state: presen

t
  become: yes

- name: install software-defined-power
  include_tasks: software_defined_power.yml
