- name: Get list of pair flag-value of all the fixed options of db_bench
  set_fact:
    db_bench_options: "{{ db_bench_fixed_options }}"


- name: Merge db_bench_options with phase db_bench options when session_options defined
  set_fact:
    db_bench_options: "{{ db_bench_fixed_options | combine(session_options[workload]) | dict2items }}"
  when: session_options[workload] is defined

- name: Only use db_bench_fixed_options
  set_fact:
    db_bench_options: "{{ db_bench_fixed_options | dict2items }}"
  when: session_options[workload] is not defined

- name: Init empty list
  set_fact:
    db_bench_options_strings: []

- name: Make string with flag command line syntax
  set_fact:
    db_bench_options_strings: "{{ db_bench_options_strings + [ '--' + (item.key|string) + '=' + (item.value|string) ] }}"
  loop: "{{ db_bench_options }}"

- name: Debug Joined String
  debug:
    msg: "{{ db_bench_options_strings | join(' ') }}"
- name: Join string to make command line flags string
  set_fact:
    db_bench_options_string: "{{ db_bench_options_strings | join(' ') }}"
