- name: Spawn dstat process
  shell: |
    source {{ bench_script }}/util.sh
    spawn-dstat-process {{ session_name }} {{ loading_results_dir }}/dstat-loading.csv

- name: run db bench setup loading
  shell: |
    source {{ bench_script }}/benchmark.sh
    run_db_bench {{ loading_execution_names[session_name] }} {{ loading_phase_num }} {{ loading_phase_threads }}
  register: loading_out

# Not the same as 2>&1 but hopefully does the job
- name: Write log
  lineinfile:
    path: "{{ loading_results_dir }}/log-loading.txt"
    line: "{{ loading_out.stdout_lines + loading_out.stderr_lines | join('\n') }}"
    create: yes
