- name: Run the base workload that is goind to serve as a comparing factor against the other workloads.
  hosts: cloud148
  vars:
    plot_directory: ../misc/memory/2024-10-15T17:25:46Z
  gather_facts: True
  roles:
    - plot_graphs
