- name: Run the base workload that is goind to serve as a comparing factor against the other workloads.
  hosts: localhost
  vars:
    session_name: test
  connection: local
  gather_facts: True
  roles:
    - set_vars_session

    - cpu_governor_performance

    - role: prepare_run_monitor_graph
      workload: delta_base_0_100
      load_backup: True
      repetitions: 1

    - role: prepare_run_monitor_graph
      workload: delta_base_0_100_zipf
      load_backup: False
      repetitions: 4
