- name: Create db and create backup or load backup and run ycsb a->b->c
  hosts: localhost
  connection: local
  gather_facts: True
  roles:
    - set_vars_session

    - role: prepare_run_monitor_graph
      workload: fillrandom_5M
      create_backup: True
      repetitions: 2

    - role: prepare_run_monitor_graph
      workload: 50-50_4T
      load_backup: True
      repetitions: 2

    - role: prepare_run_monitor_graph
      workload: Readonly_4T
      load_backup: True
      repetitions: 2

    - role: prepare_run_monitor_graph
      workload: 95-5_4T
      load_backup: True
      repetitions: 2
