- name: Run workloads that focus on memory specific options of db_bench. Maintaning a fixed set of options, in order to be able to compare the energy consequences of certain changes in the memory specific options.
  hosts: localhost
  vars:
    session_name: workload
  connection: local
  gather_facts: True
  roles:
    - set_vars_session

    - cpu_governor_performance

    #- delete_cur_db

    #- role: prepare_run_monitor_graph
    #  workload: fillrandom_100M

    #- create_backup


    ################ Start bench_workload delta test ################
    - role: prepare_run_monitor_graph
      workload: delta_B
      load_backup: True
      repetitions: 2

    - role: prepare_run_monitor_graph
      workload: delta_C
      load_backup: True
      repetitions: 2

    - role: prepare_run_monitor_graph
      workload: delta_D
      load_backup: True
      repetitions: 2


    ################ Start key_size delta test ################
    - role: prepare_run_monitor_graph
      workload: delta_key_size_64
      load_backup: True
      repetitions: 2

    - role: prepare_run_monitor_graph
      workload: delta_key_size_128
      load_backup: True
      repetitions: 2

    - role: prepare_run_monitor_graph
      workload: delta_key_size_512
      load_backup: True
      repetitions: 2

    - role: prepare_run_monitor_graph
      workload: delta_key_size_1K
      load_backup: True
      repetitions: 2

    ################ Start value_size delta test ################
    - role: prepare_run_monitor_graph
      workload: delta_value_size_512
      load_backup: True
      repetitions: 2

    - role: prepare_run_monitor_graph
      workload: delta_value_size_16K
      load_backup: True
      repetitions: 2

    - role: prepare_run_monitor_graph
      workload: delta_value_size_256K
      load_backup: True
      repetitions: 2

    - role: prepare_run_monitor_graph
      workload: delta_value_size_1M
      load_backup: True
      repetitions: 2

    ################ Start YCSB_uniform_distribution delta test ################
    - role: prepare_run_monitor_graph
      workload: delta_YCSB_uniform_distribution_false
      load_backup: True
      repetitions: 2
