- name: Run the workload specified by session_name
  hosts: localhost
  connection: local
  gather_facts: True
  roles:
    - set_vars_session

    - role: prepare_run_monitor_graph
      workload: fillrandom_100M

    - create_backup

    #- role: prepare_run_monitor_graph
    #  workload: 50-50_1T
    #  repetitions: 2
    #  load_backup: True

    #- role: prepare_run_monitor_graph
    #  workload: 50-50_2T
    #  repetitions: 2
    #  load_backup: True

    #- role: prepare_run_monitor_graph
    #  workload: 50-50_4T
    #  repetitions: 2
    #  load_backup: True

    #- role: prepare_run_monitor_graph
    #  workload: 50-50_8T
    #  repetitions: 2
    #  load_backup: True

    #- role: prepare_run_monitor_graph
    #  workload: 50-50_16T
    #  repetitions: 2
    #  load_backup: True

    #- role: prepare_run_monitor_graph
    #  workload: 50-50_32T
    #  repetitions: 2
    #  load_backup: True

    #- role: prepare_run_monitor_graph
    #  workload: 50-50_64T
    #  repetitions: 2
    #  load_backup: True

    #- role: prepare_run_monitor_graph
    #  workload: 50-50_128T
    #  repetitions: 2
    #  load_backup: True
