- name: Run workloads that focus on memory specific options of db_bench. Maintaning a fixed set of options, in order to be able to compare the energy consequences of certain changes in the memory specific options.
  hosts: localhost
  vars:
    session_name: memory
  connection: local
  gather_facts: True
  roles:
    - set_vars_session

    - cpu_governor_performance

    #- delete_cur_db

    #- role: prepare_run_monitor_graph
    #  workload: fillrandom_100M

    #- create_backup

    ################ Start cache_size delta tests ################
    - role: prepare_run_monitor_graph
      workload: delta_cache_8G
      load_backup: True
      repetitions: 2

    - role: prepare_run_monitor_graph
      workload: delta_cache_16G
      load_backup: True
      repetitions: 2

    - role: prepare_run_monitor_graph
      workload: delta_cache_32G
      load_backup: True
      repetitions: 2

    - role: prepare_run_monitor_graph
      workload: delta_cache_64G
      load_backup: True
      repetitions: 2

    ################ Start cache_index_and_filter_blocks delta tests ################
    - role: prepare_run_monitor_graph
      workload: delta_cache_index_filter_true
      load_backup: True
      repetitions: 2

    ################ Start write_buffer_size delta tests ################
    - role: prepare_run_monitor_graph
      workload: delta_write_buffer_size_64M
      load_backup: True
      repetitions: 2

    - role: prepare_run_monitor_graph
      workload: delta_write_buffer_size_256M
      load_backup: True
      repetitions: 2

    - role: prepare_run_monitor_graph
      workload: delta_write_buffer_size_512M
      load_backup: True
      repetitions: 2

    - role: prepare_run_monitor_graph
      workload: delta_write_buffer_size_1G
      load_backup: True
      repetitions: 2

    ################ Start write_buffer_size delta tests ################
    - role: prepare_run_monitor_graph
      workload: delta_max_write_buffer_number_1
      load_backup: True
      repetitions: 2

    - role: prepare_run_monitor_graph
      workload: delta_max_write_buffer_number_4
      load_backup: True
      repetitions: 2

    - role: prepare_run_monitor_graph
      workload: delta_max_write_buffer_number_8
      load_backup: True
      repetitions: 2
