- name: Run workloads that focus on memory specific options of db_bench. Maintaning a fixed set of options, in order to be able to compare the energy consequences of certain changes in the memory specific options.
  hosts: localhost
  connection: local
  gather_facts: True
  roles:
    - set_vars_session

    - cpu_governor_performance

    #- delete_cur_db

    #- role: prepare_run_monitor_graph
    #  workload: fillrandom_100M

    #- create_backup


    ################ Start flush delta tests ################
    - role: prepare_run_monitor_graph
      workload: delta_flushes_2
      load_backup: True

    - role: prepare_run_monitor_graph
      workload: delta_flushes_4
      load_backup: True

    ################ Start compaction delta tests ################
    - role: prepare_run_monitor_graph
      workload: delta_compactions_1
      load_backup: True

    - role: prepare_run_monitor_graph
      workload: delta_compactions_2
      load_backup: True

    - role: prepare_run_monitor_graph
      workload: delta_compactions_8
      load_backup: True

    - role: prepare_run_monitor_graph
      workload: delta_compactions_16
      load_backup: True

    ################ Start foreground threads delta tests ################

    - role: prepare_run_monitor_graph
      workload: delta_1T
      load_backup: True

    - role: prepare_run_monitor_graph
      workload: delta_2T
      load_backup: True

    - role: prepare_run_monitor_graph
      workload: delta_4T
      load_backup: True

    - role: prepare_run_monitor_graph
      workload: delta_8T
      load_backup: True

    - role: prepare_run_monitor_graph
      workload: delta_32T
      load_backup: True

    - role: prepare_run_monitor_graph
      workload: delta_64T
      load_backup: True

    - role: prepare_run_monitor_graph
      workload: delta_128T
      load_backup: True
