- name: Run the workload specified by session_name
  hosts: localhost
  connection: local
  gather_facts: True
  roles:
    - set_vars_session

    - load_backup

    - role: prepare_run_monitor_graph
      workload: 50-50_1T
      repetitions: 2

    - load_backup

    - role: prepare_run_monitor_graph
      workload: 50-50_2T

    #- load_backup

    #- role: prepare_run_monitor_graph
    #  workload: 50-50_4T


    #- load_backup

    #- role: prepare_run_monitor_graph
    #  workload: 50-50_8T


    #- load_backup

    #- role: prepare_run_monitor_graph
    #  workload: 50-50_16T
