- name: Run workloads that focus on concurrency specific options of db_bench. Maintaning a fixed set of options, in order to be able to compare the energy consequences of certain changes in the concurrency specific options.
  hosts: localhost
  vars:
    session_name: compaction-levels-test
  connection: local
  gather_facts: True
  roles:
    - set_vars_session

    - cpu_governor_performance

    #- delete_cur_db
    #- role: prepare_run_monitor_graph
    #  workload: fillrandom_200M
    #- create_backup

    - role: prepare_run_monitor_graph
      workload: delta_128T
      load_backup: True
      repetitions: 1

    #- role: prepare_run_monitor_graph
    #  workload: delta_8T
    #  load_backup: True
    #  repetitions: 2
