- name: Run the workload specified by session_name
  hosts: cloudinha
  gather_facts: True
  roles:
    - set_vars_session

    - set_workload_ycsbfill_5M
    - set_vars_workload
    - add_fixed_options
    - cool_down_sleep
    - clean_heap
    - spawn_dstat_process
    - run_db_bench
    - join_dstat_process

    - set_workload_write_intensive
    - set_vars_workload
    - add_fixed_options
    - cool_down_sleep
    - clean_heap
    - spawn_dstat_process
    - run_db_bench
    - join_dstat_process
