- name: Restructure results filesystem structure
  hosts: localhost
  gather_facts: false
  vars:
    base_dir_var: "/home/jpdiasfernandes/.tmp"
  tasks:
    - name: Restructure filesystem structure
      update_results_fs:
        base_dir:  "{{base_dir_var}}"
