- name: Spawn dstat process for jammy ubuntu (22.04)
  shell: |
    screen -S {{ dstat_screen_name }} -d -m pcp dstat -tcdm --noheaders --output {{ dstat_output_file }}
  async: 0
  when: hostvars[inventory_hostname]["ansible_distribution"] == "Ubuntu" and hostvars[inventory_hostname]["ansible_distribution_version"] == "22.04"

- name: Spawn dstat process for ubuntu 20.04
  shell: |
    screen -S {{ dstat_screen_name }} -d -m dstat -tcdm --noheaders --output {{ dstat_output_file }}
  async: 0
  when: hostvars[inventory_hostname]["ansible_distribution"] == "Ubuntu" and hostvars[inventory_hostname]["ansible_distribution_version"] == "20.04"


- name: Spawn temperature logger process
  shell: |
    screen -S {{ temp_screen_name }} -d -m python3 {{utils_dir}}/temp_logger.py {{ temp_output_file }}

- name: Spawn energy logger process
  shell: |
    screen -S {{ energy_screen_name }} -d -m sudo python3 {{utils_dir}}/energy_logger.py {{ energy_output_file }}
