- name: Spawn dstat process
  shell: |
    screen -S {{ dstat_screen_name }} -d -m pcp dstat -tcdm --noheaders --output {{ dstat_output_file }}
  async: 0

- name: Spawn temperature logger process
  shell: |
    screen -S {{ temp_screen_name }} -d -m python3 {{utils_dir}}/temp_logger.py {{ temp_output_file }}


#- name: Ensure service is created
#  copy:
#   src: monitor-server.service
#   dest: /etc/systemd/system/monitor-server.service
#  become: true
#
#- name: Spaen energy logger
#  systemd_service:
#    state: started
#    name: monitor-server.service
#  become: true

- name: Spawn energy logger
  shell: |
    screen -S {{ energy_screen_name }} -d -m sudo {{energy_tool_server}}
  args:
    chdir: "{{ workload_results_dir }}"
