- name: Clone software-defined-power
  git:
    repo: "git@github.com:jpdiasfernandes/software-defined-power.git"
    dest: "{{ energy_tool_dir }}"
    version: main

- name: Build software-defined-power
  shell: |
    cmake -S{{energy_tool_dir}} -B{{energy_tool_bin}}
    cmake --build {{energy_tool_bin}} -j4
    sudo cmake --install {{energy_tool_bin}}
