- name: Clone software-defined-power
  git:
    repo: "git@github.com:jpdiasfernandes/software-defined-power.git"
    dest: "{{ energy_tool_dir }}"

- name: Build software-defined-power
  shell: |
    cmake -S{{energy_tool_dir}} -B{{energy_tool_bin}}
    cmake --build {{energy_tool_bin}}
    sudo cmake --install {{energy_tool_bin}}
