- name: Pcp version
  shell: |
    pcp dstat --version | head -1 | grep -Eo "[0-9]+\\.[0-9]+\\.[0-9]+"
  register: pcp_version

- name: Fix pcp dstat output csv when versions is lower than 5.2.5
  shell: |
    python3 {{utils_dir}}/fix_pcp_dstat.py {{dstat_output_file}}
  when: pcp_version.stdout_lines[0] is version('5.2.5', '<')

- name: Plot dstat graphs
  shell: |
    python3 {{utils_dir}}/plot.py {{dstat_output_file}}

- name: Plot throughput graph
  shell: |
    python3 {{utils_dir}}/plot_throughput.py {{bench_log}}

- name: Plot temperature graph
  shell: |
    python3 {{utils_dir}}/plot_temp.py {{temp_output_file}}

- name: Plot energy reports
  generate_energy_report:
    energy_file: "{{ pid_energy_file }}"
    event_file: "{{ rocksdb_log_file }}"
    chdir: "{{ workload_results_dir }}"
    output: "{{ energy_report_file }}"
  ignore_errors: true
