
- name: Plot dstat graphs
  shell: |
    python3 {{utils_dir}}/plot.py {{dstat_output_file}}

- name: Plot throughput graph
  shell: |
    python3 {{utils_dir}}/plot_throughput.py {{bench_log}}

- name: Plot temperature graph
  shell: |
    python3 {{utils_dir}}/plot_temp.py {{temp_output_file}}

- name: Find process name
  shell: |
     ls -t pid-*.csv | head -1
  args:
    chdir: "{{ workload_results_dir }}"
  register: energy_pid_file


- name: Debug last pid measurement
  debug:
    msg: "{{ energy_pid_file.stdout_lines[0] | trim }}"


- name: Plot energy graph
  plot_energy:
    energy_file: "{{ energy_pid_file.stdout_lines[0] | trim }}"
    event_file: "{{rocksdb_log}}"
    chdir: "{{ workload_results_dir }}"
    output_prefix: "{{energy_output_file}}"

  register: out_plot_energy
  ignore_errors: True

