
- name: Plot dstat graphs
  shell: |
    python3 {{utils_dir}}/plot.py {{dstat_output_file}}

- name: Plot throughput graph
  shell: |
    python3 {{utils_dir}}/plot_throughput.py {{bench_log}}

- name: Plot temperature graph
  shell: |
    python3 {{utils_dir}}/plot_temp.py {{temp_output_file}}

- name: Plot energy graph
  shell: |
    python3 {{utils_dir}}/plot_energy.py {{energy_output_file}}
