#
# For now it will not be able to add aditional flags just to test the setup1 workload
# Pipe operation has precedence when it comes to division
- name: Call db_bench
  shell: |
    sudo numactl -N {{ numa_node_set }} -m {{ numa_node_set }} \
    systemd-run --setenv=LD_PRELOAD={{ energy_tool_client }} --scope -p MemoryLimit={{ memory_limit }} -p MemoryAccounting=true \
    {{ build_dir }}/db_bench --benchmarks="{{ bench_workload_name }},sstables" \
                             --num={{ ( (num_operations|int)/ (num_threads|int) ) | round | int}} \
                             --threads={{ num_threads }} \
                             --db={{db_dir}} \
                             {{ db_bench_options_string }}
  args:
    chdir: "{{ session_results_dir }}"
  become: yes
  register: execution_out

- name: Write db_bench log
  lineinfile:
    path: "{{ bench_log }}"
    line: "{{ (execution_out.stderr_lines + execution_out.stdout_lines) | join('\n') }}"
    create: yes
