- name: set repetitions if not defined
  set_fact:
    repetitions: 1
  when: repetition is not defined

- name: Call the roles
  include_role:
    name: "{{roleinputvar}}"
  loop: "{{ [ 'set_vars_workload', 'add_fixed_options', 'add_options_workload', 'cool_down_sleep', 'clean_heap', 'spawn_monitoring', 'run_db_bench', 'join_monitoring', 'plot_graph' ] * repetitions }}"
  loop_control:
    loop_var: roleinputvar
