- name: Clean OS heap (clean page and swap)
  ansible.builtin.shell: |
   free -m
   sudo sync; sudo sh -c "echo 3 > /proc/sys/vm/drop_caches"
   sudo swapoff -a
   sudo swapon -a
   free -m
  become: yes
