- name: Set loading_results_dir
  set_fact:
    loading_results_dir: "{{ workload_results_dir }}/loading"

- name: Create  directory for loading_results_dir if it does not exist
  ansible.builtin.file:
    path: "{{ loading_results_dir }}"
    state: directory

- name: Set num_threads to loading_phase_threads
  set_fact:
    num_threads: "{{ loading_phase_threads }}"

- name: Set num_operations to loading_phase_num
  set_fact:
    num_operations: "{{ loading_phase_num }}"

- name: Set workload to setup_loading_names workload
  set_fact:
    workload: "{{ setup_loading_names[session_name] }}"

- name: Set dstat_output_file to loading_results_dir/dstat-loading.csv
  set_fact:
    dstat_output_file: "{{ loading_results_dir }}/dstat-loading.csv"


- name: Get session map for variable db_bench options
  set_fact:
    session_options: "{{ db_bench_session_options[session_name ]}}"
  when: db_bench_session_options[session_name] is defined

- name: Get loading options map from  session_options
  set_fact:
    session_phase_options: "{{ session_options['loading'] | dict2items }}"
  when: session_options['loading'] is defined
