- name: call ansible playbook
  shell: |
    screen -S ansible_remote -L -d -m /home/gsd/.local/bin/ansible-playbook -i inventory.yml {{ playbook}} -v
  async: 604800
  poll: 30
  args:
    chdir: "{{ kvbench_dir }}"
