- name: Get uname -r 
  shell: uname -r 
  register: uname_output

- name: Set uname_r
  set_fact:
    uname_r: "{{ uname_output.stdout_lines[0] }}"

- name: Update inventory.yml
  template:
    src: inventory_template.j2
    dest: inventory.yml
  delegate_to: localhost
