- name: Join dstat process
  shell: |
    screen -X -S {{ dstat_screen_name }} stuff "^C"

- name: Join temperature process
  shell: |
    screen -X -S {{ temp_screen_name }} stuff "^C"

#Most likely the process would have exited on its own. Just try to
#join, if it fails it already exited.
- name: Join io process
  shell: |
    screen -X -S {{ io_screen_name }} stuff "^C"
  ignore_errors: True

- name: Join energy process
  shell: |
    screen -X -S {{ energy_screen_name }} stuff "^C"

#Since software-defined-power does not yet implement a output file option

- name: move sys.csv to sys_energy_file location
  command: mv "{{workload_results_dir}}/sys.csv" "{{sys_energy_file}}"
  args:
    creates: "{{sys_energy_file}}"
    removes: "{{workload_results_dir}}/sys.csv"

- name: move pid-num.csv to pid-energy.csv
  shell: |
    mv {{workload}}/pid-*.csv {{pid_energy_file}}
  args:
    creates: "{{pid_energy_file}}"

- name: move all_events.log to rocksdb_log_file location
  command: mv "{{workload_results_dir}}/all_events.log" "{{rocksdb_log_file}}"
  args:
    creates: "{{rocksdb_log_file}}"
    removes: "{{workload_results_dir}}/all_events.log"

- name: move hardware.csv to sys_hardware_file location
  command: mv "{{workload_results_dir}}/hardware.csv" "{{sys_hardware_file}}"
  args:
    creates: "{{sys_hardware_file}}"
    removes: "{{workload_results_dir}}/hardware.csv"

- name: cp db_dir/LOG to db_log_file location
  command: cp "{{db_dir}}/LOG" "{{db_log_file}}"
  args:
    creates: "{{db_log_file}}"
