- name: Join dstat process
  shell: |
    screen -X -S {{ dstat_screen_name }} stuff "^C"

- name: Join temperature process
  shell: |
    screen -X -S {{ temp_screen_name }} stuff "^C"

- name: Join energy process
  shell: |
    screen -X -S {{ energy_screen_name }} stuff "^C"

#Rename sys.csv to sys_energy_file
#Since software-defined-power does not yet implement a output file option

- name: move sys.csv to sys_energy_file location
  command: mv "{{workload_results_dir}}/sys.csv" "{{sys_energy_file}}"
  args:
    creates: "{{sys_energy_file}}"
    removes: "{{workload_results_dir}}/sys.csv"

- name: move all_events.log to rocksdb_log_file location
  command: mv "{{workload_results_dir}}/all_events.log" "{{rocksdb_log_file}}"
  args:
    creates: "{{rocksdb_log_file}}"
    removes: "{{workload_results_dir}}/all_events.log"
