#Requires db_bench_options_string calculation

- name: Get all workload that have the pattern of the options used
  find:
    paths: "{{workload_results_dir}}"
    file_type: file
    use_regex: yes
    patterns: "options\\.log"
  register: find_options

- name: if does not exist then create file with db_bench options
  lineinfile:
    path: "{{workload_results_dir}}/options.log"
    line: "DB_BENCH OPTIONS: \n\t{{ db_bench_options_strings | join('\n\t')}}\nWORKLOAD_NAME: {{bench_workload_name}}\nNUM_OPERATIONS: {{num_operations}}\nNUM_FOREGROUND_THREADS: {{num_threads}}\nCOOL_DOWN_TIME: {{ cool_down_time }}\nMEMORY_LIMIT: {{memory_limit}}\nNUMA_NODE_SET: {{ numa_node_set }}\nALLOWED_SDPOWER_CPUS: {{allowed_cpus}}"
    create: yes
  when: find_options['matched'] == 0
