- name: set num_threads to workload threads
  set_fact:
    num_threads: "{{ workload_settings[workload]['threads']}}"

- name: set num_operations to workload num_operations
  set_fact:
    num_operations: "{{ workload_settings[workload]['num_operations'] }}"

- name: set bench_workload to workload bench_workload_name
  set_fact:
    bench_workload_name : "{{workload_settings[workload]['bench_workload_name']}}"

- name: set cool_down_time to workload cool_down_time
  set_fact:
    cool_down_time: "{{workload_settings[workload]['cool_down_time']}}"
- name: get stat from dstat_output_file for this workload
  stat:
    path: "{{ session_results_dir }}/dstat-{{workload}}.csv"
  register: dstat_file_status


# Workloads output files
- name: Get all dstat files that have the pattern of the same workload
  find:
    paths: "{{session_results_dir}}"
    file_type: file
    use_regex: yes
    patterns: "dstat-{{workload}}(-[0-9]+)?\\.csv"
  register: find_dstat

- name: Debug find dstat result
  debug:
    msg: "{{find_dstat}}"

- name: set dstat_output_file when find_dstat.matched == 0
  set_fact:
    dstat_output_file: "{{session_results_dir}}/dstat-{{workload}}.csv"
  when: find_dstat['matched'] == 0

- name: set dstat_output_file when find_dstat.matched != 0
  set_fact:
    dstat_output_file: "{{session_results_dir}}/dstat-{{workload}}-{{find_dstat['matched']}}.csv"
  when: find_dstat['matched'] != 0

- name: Get all temperature log files that have the pattern of the same workload
  find:
    paths: "{{session_results_dir}}"
    file_type: file
    use_regex: yes
    patterns: "temp-{{workload}}(-[0-9]+)?\\.csv"
  register: find_temp

- name: set temp_output_file when find_temp.matched == 0
  set_fact:
    temp_output_file: "{{session_results_dir}}/temp-{{workload}}.csv"
  when: find_temp['matched'] == 0

- name: set temp_output_file when find_temp.matched != 0
  set_fact:
    temp_output_file: "{{session_results_dir}}/temp-{{workload}}-{{find_temp['matched']}}.csv"
  when: find_temp['matched'] != 0

- name: Get all energy log files that have the pattern of the same workload
  find:
    paths: "{{session_results_dir}}"
    file_type: file
    use_regex: yes
    patterns: "energy-{{workload}}(-[0-9]+)?\\.csv"
  register: find_energy

- name: set energy_output_file when find_energy.matched == 0
  set_fact:
    energy_output_file: "{{session_results_dir}}/energy-{{workload}}.csv"
  when: find_energy['matched'] == 0

- name: set energy_output_file when find_energy.matched != 0
  set_fact:
    energy_output_file: "{{session_results_dir}}/energy-{{workload}}-{{find_energy['matched']}}.csv"
  when: find_energy['matched'] != 0

- name: Get all db-bench-log files that have the pattern of the same workload
  find:
    paths: "{{session_results_dir}}"
    file_type: file
    use_regex: yes
    patterns: "bench-log-{{workload}}(-[0-9]+)?\\.log"
  register: find_bench

- name: Debug find bench result
  debug:
    msg: "{{find_bench}}"

- name: set bench_log when find_bench.matched == 0
  set_fact:
    bench_log: "{{session_results_dir}}/bench-log-{{workload}}.log"
  when: find_bench['matched'] == 0

- name: set bench_log when find_bench.matched != 0
  set_fact:
    bench_log: "{{session_results_dir}}/bench-log-{{workload}}-{{find_bench['matched']}}.log"
  when: find_bench['matched'] != 0


# screen session name variables
- name: Set dstat screen session name
  set_fact:
    dstat_screen_name: "dstat-{{ session_name }}-{{hostvars[inventory_hostname]['ansible_date_time']['iso8601']}}"

- name: Set temperature screen session name
  set_fact:
    temp_screen_name:  "temp-{{ session_name }}-{{hostvars[inventory_hostname]['ansible_date_time']['iso8601']}}"

- name: Set energy screen session name
  set_fact:
    energy_screen_name:  "energy-{{ session_name }}-{{hostvars[inventory_hostname]['ansible_date_time']['iso8601']}}"

- name: Get session map for variable db_bench options
  set_fact:
    session_options: "{{ db_bench_session_options[workload] | dict2items }}"
  when: db_bench_session_options[workload] is defined
