- name: Call script to create summary for this test
  log_summary_info:
    energy_file: "{{ pid_energy_file }}"
    event_file: "{{ rocksdb_log_file }}"
    throughput_file: "{{ bench_log }}"
    chdir: "{{ workload_results_dir }}"
