- name: Clone kvbench
  git:
    repo: "https://github.com/jpdiasfernandes/kvbench.git"
    dest: "{{ kvbench_dir }}"
    version: main

- name: Ensure ~/.ansible/plugins/module_utils
  file:
    path: "~/.ansible/plugins/module_utils"
    state: directory

- name: Ensure ~/.ansible/plugins/modules exists
  file:
    path: "~/.ansible/plugins/modules"
    state: directory

- name: Copy utils scripts to utils path
  copy:
    src: "{{ kvbench_dir }}/utils/"
    dest: "{{ utils_dir }}/"
    remote_src: yes

- name: copy module scripts to modules ansible path
  copy:
    src: "{{ kvbench_dir }}/modules/"
    dest: "~/.ansible/plugins/modules/"
    remote_src: yes

- name: copy module utils to modules utils ansible path
  copy:
    src: "{{ kvbench_dir }}/module_utils/"
    dest: "~/.ansible/plugins/module_utils/"
    remote_src: yes

