- name: Clone rocksdb from personal fork
  git:
    repo: "https://github.com/jpdiasfernandes/rocksdb.git"
    dest: "{{ source_dir }}"
    version: 8.7.fb

- name: Build rocksdb
  shell: |
    cmake -DWITH_SNAPPY=ON -DWITH_LZ4=ON -DWITH_ZSTD=ON -DWITH_ZLIB=ON -DWITH_BZ2=ON -DCMAKE_BUILD_TYPE=Release -DUSE_RTTI=true -B build -S .
    cmake --build build -- -j 4
  args:
    chdir: "{{ source_dir }}"
