- name: Create directory for db if it does not exist
  file:
    path: "{{ db_dir }}"
    state: directory

- name: Copy backup to db
  shell: |
    sudo rsync --info=progress2 -r -a {{db_backup_dir}}/* {{db_dir}}
